### ISSUE TITLE
remote sources not working with jquery 3.1.1

### ISSUE THREAD

**Issue by andrewharvey** [corejavascript/typeahead.js#150]
When using a remote source with jquery 3.1.1 I get this error:
```
Uncaught TypeError: this._send is not a function
    at Transport._get (typeahead.bundle.js:397)
    at later (typeahead.bundle.js:113)
```

It works fine with jquery 1.9.1.

**Comment by judowalker** [comment]
I'm using a remote source with jQuery 3.2.1 and it works for me. I haven't tried 3.1.1 but maybe you can try it with the latest version of jQuery.

**Comment by jlbooker** [comment]
@andrewharvey Please try the latest version of Typeahead (1.2.0). It adds support for jQuery 3.

If it's still not working, please provide a jsfiddle we can use to reproduce the problem and test with.

**Comment by andrewharvey** [comment]
Thanks @jlbooker I'll give this a go next time I use typeahead.

**Comment by amiraliakbari** [comment]
I had the same error. It was because of using slim version of JQuery which does not include ajax functionalities. Switching to default JQuery version will solve the problem, but it is good to have a note in docs or even a runtime check for `$.ajax`.
